### PR TITLE
Feat/commit built files

### PR DESCRIPTION
**Pull request by maxweldsouza**
I keep forgetting to commit built files when cutting a release. This PR ensures that semantic release automatically builds and commits built files from CI. 

I tested this by releasing v4.8.0-beta.8 https://github.com/Maxihost/metal-ui/commit/9f5a0c39395eb0b11c4094d7bf8f0888dc5bcbec

### CODE REVIEW

**Review by marcelo-sousa-mh — APPROVED** [review]
@maxweldsouza great addition! I was also struggling with this step

**Comment by esoubihe** [comment]
This one's long overdue. Thanks for picking it up

**Comment by esoubihe** [comment]
@maxweldsouza LGTM, feel free to merge

**Comment by maxweldsouza** [comment]
Thanks, @esoubihe, and @marcelo-sousa-mh! Merging.

**Pull request merged**
