### PR TITLE
fix: Box story and background color

### PR DESCRIPTION
**Pull request by maxweldsouza**
This PR removes the white background class from Box which was preventing the background color from being overridden.
I can't think of a clean way to make this default to a white background. It's best to pass it in.

This PR also removes ref forwarding on Box. For some reason it was breaking storybook.

### CODE REVIEW

**Comment by esoubihe** [comment]
> This PR removes the white background class from Box which was preventing the background color from being overridden. I can't think of a clean way to make this default to a white background. It's best to pass it in.
> 
> This PR also removes ref forwarding on Box. For some reason it was breaking storybook.

Can't we just keep the backgroundColor prop and set white as the default one? It's not a breaking change and addresses the problem

**Comment by maxweldsouza** [comment]
I've added the backgroundColor prop back but it is still a breaking change. We can't use string concatenation here because it breaks purging. We could maintain a list of background colors and switch but it will be hard to maintain. Another option is to dynamically interpolate to inline styles which is a bit messy.

**Comment by maxweldsouza** [comment]
I'm not happy about this approach because anyone who uses the Box component with an overridden background needs to have emotion as well as tailwind.css installed. Having an external CSS file is a huge performance hit. I would much prefer to use CSS in JS throughout an application. We could consider using styled(Box) to override styles instead of className.

There are some other downsides to the Box component:
There's no media query support.
It does not support gap.
There is a performance hit because it brings in JS for things that can be done with pure css.
It is not easy to switch from grid to flex and vice versa.

**Comment by esoubihe** [comment]
> anyone who uses the Box component with an overridden background needs to have emotion as well as tailwind.css installed.

Not necessarily. If you set any any class with a `background-color` rule you should be able to get it working, no matter which lib you're using.

> There's no media query support.
> It does not support gap.
> There is a performance hit because it brings in JS for things that can be done with pure css.
> It is not easy to switch from grid to flex and vice versa.

I think these can be easily addressed. Media query could be built into the component, thus avoiding more HTML and having more consistency. For grid layouts, we want a different component. Usually two primitives are used to compose layouts, here's a reference: https://evergreen.segment.com/foundations/layers

I agree maintaining this primitive is not straightforward, but I just can't see much benefit in ditching it in favor of plain html, especially considering `Box` is used in many other components

**Comment by esoubihe** [comment]
@maxweldsouza Is this solution acceptable? I'm okay with discussing the need of the Box component but now this is blocking a release so let's get this going and discuss separately

**Comment by maxweldsouza** [comment]
Sure. I gave my go ahead above. Do you want me to merge and release this?

**Pull request merged**
