### PR TITLE
Feedback Storybook and Classes

### PR DESCRIPTION
**Pull request by esoubihe**
Initial work to add the Feedback widget to Storybook and move from Geist to Tailwindcss. 

There is still some work to do for the markup to be complete but about 80% is done here. Once the state is fixed with our Input and Textarea components, it should be easier to bring the remaining classes to the component.

### CODE REVIEW

**Comment by esoubihe** [comment]
LGTM

**Comment by leonardorisch** [comment]
Finishing some style issues and JS events, click outside is not working properly

**Comment by leonardorisch** [comment]
@esoubihe could you fix the last style issues? it is working now

**Comment by esoubihe** [comment]
> @esoubihe could you fix the last style issues? it is working now

Will do, thanks

**Comment by esoubihe** [comment]
Can you please check this is working? Storybook just gives me a blank screen and a console error.

```
WARN Maybe your glob was invalid?
WARN see: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
(node:64055) DeprecationWarning: You're specified an invalid glob, we've attempted to fix it, please ensure the glob you specify is a valid glob. See: https://github.com/storybookjs/storybook/blob/next/MIGRATION.md#correct-globs-in-mainjs
(Use `node --trace-deprecation ...` to show where the warning was created)
```

**Comment by esoubihe** [comment]
@leonardorisch Pushed the final style adjustments. Can be merged to #91 if everything looks good here.

**Comment by leonardorisch** [comment]
looks great :star_struck:

**Pull request merged**
