### PR TITLE
chore(style): Standardizes classes between Input, Select and TextArea

### PR DESCRIPTION
**Pull request by esoubihe**
- Adds @tailwindcss/forms
- Standardizes classes between different form elements

### CODE REVIEW

**Review by n23daniel — COMMENTED** [review]
Looks great! One other thing I noticed though, what do you think of also removing the focus outline for the AlgoliaSearch? 
Screenshot 2021-03-25 at 23 46 36

**Comment by esoubihe** [comment]
> Looks great! One other thing I noticed though, what do you think of also removing the focus outline for the AlgoliaSearch?
> Screenshot 2021-03-25 at 23 46 36

Just pushed a change to `Input` that prevents outlines on all input types. Also decided to remove the `dark` prop. I think this should either be done on a separate work to support dark mode for multiple components or should be done on the `Input` component. Wdyt?

**Comment by n23daniel** [comment]
> > Looks great! One other thing I noticed though, what do you think of also removing the focus outline for the AlgoliaSearch?
> > Screenshot 2021-03-25 at 23 46 36
> 
> Just pushed a change to `Input` that prevents outlines on all input types.

Nice!

> Also decided to remove the `dark` prop. I think this should either be done on a separate work to support dark mode for multiple components or should be done on the `Input` component. Wdyt?

Agree!

One more thing though - there should be a commit with a `fix` message for the semantic-release to bump the version to 2.6.2, it won't get published with `chore` commits. Unless you want to release this changes with other fixes/improvements sometime in the future.

**Comment by esoubihe** [comment]
> One more thing though - there should be a commit with a `fix` message for the semantic-release to bump the version to 2.6.2, it won't get published with `chore` commits. Unless you want to release this changes with other fixes/improvements sometime in the future.

Thanks, I do plan to release that with other features.

**Pull request merged**
