### PR TITLE
Feat/pd 2119 radio group

### PR DESCRIPTION
**Pull request by marcelo-sousa-mh**
This PR adds a RadioGroup component to the library.

It is based in [Radix UI RadioGroup Primitive](https://www.radix-ui.com/docs/primitives/components/radio-group) and keeps a very similar API, except for few details listed ahead.

We're using ContextAPI instead of a simple prop drilling in order to not rely on an immutable structure and have more flexibility. For example: we currently have a use cases where we have a <Collapsible /> element to split the options of Servers in two parts and this would be very impractical to achieve without ContextAPI since the options consume props from the RadioGroup parent. 

### Features

This component supports the following layout options:

**variant**: `default` or `card` : controls how the RadioGroup options will be shown

 
**display**: `list` or `grid`: controls the disposition of the RadioGroup options. `list` is the default value.

### Usage example
```
import {
  RadioGroup,
  RadioGroupItem,
  RadioGroupTitle,
  RadioGroupDescription,
} from '@maxihost/metal-ui/dist/RadioGroup'
...
 <RadioGroup 
    defaultValue="option-1"
  >
   <RadioGroupItem id="option-1" value="option-1">
     <RadioGroupTitle htmlFor="option-1">
       Option 1
      </RadioGroupTitle> 
      <RadioGroupDescription> Optional Description </RadioGroupDescription>
   </RadioGroupItem>  
 <RadioGroupItem id="option-1" value="option-2">
     <RadioGroupTitle htmlFor="option-2>
       Option 2
      </RadioGroupTitle>  
   </RadioGroupItem>  
</RadioGroup>
```

Results in 

image

### Changes from Radix UI 

Most of the API is still the same, there's a few changes

- `orientation` and `dir` props of the Root element will have little to no effect. Since they affect layout,  our styling would override or conflict with them. `dir` can be used as a `row-reverse`, but note we're not using it to the `card` variant, it didn't work out well.
- The `Indicator` component was suppressed to avoid repetitive imports. It will be appended automatically to every `RadioGroupItem`, unless the prop `showIndicator` is set to `false` (Note: this works only for `card` variant)

### Improvements to make

- For this first version animations were omitted. We can think more carefully in the future and have transitions that follow the look and feel of the library
- The `RadioGroupTitle` has a dubious naming. It is actually used as a label, but it also serves as a styled element to reinforce consistency.  But sometimes we don't want it to be a label, like below, where the pricing also uses this component but is not a meaningful label. We have a prop `asLabel` set to `false` in order to render the component as a Text instead of a Label. I feel styling and function in this case are overlapping. 
image

- In the same vein as above, I'm not sure if `display` prop was a good idea. Again, we may be facing a conflict of attributions. The pro of this prop is we can normalize how every RadioGroup will be presented, but we're limited to the ways we can do this (for example, grid has always 3 columns at most) and adding more props to control details would miss the point of this component and add unnecessary complexity. If we need to provide more display options, then I believe moving this control to the parent element or setting it via `className` would be the way to go.

- We need to test an integration with an uncontrolled form to make sure `name` and `required` are working as expected

### CODE REVIEW

**Review by esoubihe — COMMENTED** [review]
Nice addition

Is it the component's responsibility to set the grid size? I can see it working if we intend to keep the radio group less flexible, in which case I'd suggest the grid RadioGroup be used for items with less content, and increase the number of options per row with `grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4`. Wdyt?

Also, should the component handle icons?

**Comment by marcelo-sousa-mh** [comment]
> Nice addition
> 
> Is it the component's responsibility to set the grid size? I can see it working if we intend to keep the radio group less flexible, in which case I'd suggest the grid RadioGroup be used for items with less content, and increase the number of options per row with `grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4`. Wdyt?

It's actually these settings we're currently using. The screenshot above was taken in a `sm` context.
```
display === "grid" && tw`grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-3 gap-x-4`
```
> 
> Also, should the component handle icons?

Only the `check` icon, which is present on the card display. I've reused the icon we had previously, but I think we are already using an Icons library, right? Maybe for consistency we should import check icon from HeroIcons instead of using our own instance. I haven't seen it being used by an exported component yet, but I think it should be no problem. Wdy?

**Comment by esoubihe** [comment]
> Only the `check` icon, which is present on the card display. I've reused the icon we had previously, but I think we are already using an Icons library, right? Maybe for consistency we should import check icon from HeroIcons instead of using our own instance. I haven't seen it being used by an exported component yet, but I think it should be no problem. Wdy?

I agree. 

Should we just increase the number of items per row since these cards won't have much content? Maybe something like
`grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-x-4`

**Comment by marcelo-sousa-mh** [comment]
> Should we just increase the number of items per row since these cards won't have much content? Maybe something like `grid-cols-1 xs:grid-cols-2 sm:grid-cols-3 lg:grid-cols-4 gap-x-4`

It would't work for the layout we currently have on Create Servers, we would need to make it larger. Otherwise yes, I think 4 cols would make more sense.
What we can try is a more robust grid system with something like `repeat(auto-fit, minmax(200px, 1fr))`, so it will fit as many columns as possible keeping a minimum width for each

image

**Comment by esoubihe** [comment]
Got it. We do intend to make improvements to that page and increase the width of the content, so I think 4 items makes more sense.

**Comment by marcelo-sousa-mh** [comment]
> Got it. We do intend to make improvements to that page and increase the width of the content, so I think 4 items makes more sense.

You think we could try `minmax` for this grid? Since tw is based on screen media-queries, there's a risk we end up with a cluttered grid because of a narrow parent. Using minmax instead the column count will adapt to the available space

**Comment by esoubihe** [comment]
> > Got it. We do intend to make improvements to that page and increase the width of the content, so I think 4 items makes more sense.
> 
> You think we could try `minmax` for this grid? Since tw is based on screen media-queries, there's a risk we end up with a cluttered grid because of a narrow parent. Using minmax instead the column count will adapt to the available space

Yes, I think that could work well!

**Comment by marcelo-sousa-mh** [comment]
The `collapsed` option had to be a string instead of a boolean due to React alerts regarding the use of boolean in unknown props. The suggested solution is turning the boolean into a string. If you happen to know some other way where we can keep the prop as `bool`, let me know!

`collapsed: PropTypes.oneOf(["true", "false"])`

**Comment by marcelo-sousa-mh** [comment]
A better use of `contextAPI` made it possible to keep `collapsed` as a boolean, as it should. At first I was mixing props inheritance with context, now we have useContext all over.

**Pull request merged**
