### PR TITLE
fix: removing left padding on first td and th on row

### PR DESCRIPTION
**Pull request by marcelo-sousa-mh**
This PR removes padding-left on the first td/th of each row. This way we fix the alignment, as pointed by @esoubihe  on [PD-2369](https://maxihost.atlassian.net/browse/PD-2369)

image

### CODE REVIEW

**Comment by marcelo-sousa-mh** [comment]
@maxweldsouza I'm suggesting to merge this to #401 so we can have a single release for both fixes. Makes sense?

**Review by maxweldsouza — APPROVED** [review]
Sure.

**Pull request merged**
