### PR TITLE
feat: Algolia Search

### PR DESCRIPTION
**Pull request by JarrodMFlesch**
- Updates React to 16.8
- Adds `AlgoliaSearch` component that takes the following props

<table>
  <tr>
     <th>Prop Name</th>
     <th>Prop Type</th>
  </tr>
  <tr>
     <td>ALGOLIA_APP_ID</td>
     <td>String (Required)</td>
  </tr>
  <tr>
     <td>ALGOLIA_API_SEARCH_KEY</td>
     <td>String (Required)</td>
  </tr>
  <tr>
     <td>indices</td>
     <td>Array Of Objects (Required)</td>
   </tr>
   <tr>
     <td>indices.indexName</td>
     <td>String (Required)</td>
   </tr>
   <tr>
     <td>indices.displayName</td>
     <td>String (Required)</td>
   </tr>
   <tr>
     <td>indices.renderCardInfo</td>
     <td>Function (Required)</td>
   </tr>
   <tr>
     <td>indices.searchConditions</td>
     <td>Array Of Objects (Optional)</td>
   </tr>
   <tr>
     <td>indices.searchConditions.conditionType</td>
     <td>String (Optional) One of ['AND', 'OR'] - Defaults to 'AND'</td>
   </tr>
   <tr>
     <td>indices.searchConditions.conditionString</td>
     <td>String (Required)</td>
   </tr>
   <tr>
     <td>indices.formatHitURL</td>
     <td>Function (Required)</td>
   </tr>
   <tr>
     <td>searchOperators</td>
     <td>Array of Strings (Required) example: ['<', '=', '>', '>=', '<=']</td>
   </tr>
   <tr>
     <td>specialChar</td>
     <td>String (Required)</td>
   </tr>
   <tr>
     <td>scrollWindowHeight</td>
     <td>Number (Optional) height of the scrollable area</td>
   </tr>
   <tr>
     <td>customLoader</td>
     <td>Component to render in place of the default <b>Loader</b> (Optional)</td>
   </tr>
   <tr>
     <td>customNoResults</td>
     <td>Component to render in place of the default <b>NoResults</b> (Optional)</td>
   </tr>
</table>

Example Component
``` 
<AlgoliaSearch
    ALGOLIA_APP_ID=""
    ALGOLIA_API_SEARCH_KEY=""
    indices={[{
      indexName: 'devices',
      displayName: 'Devices', 
      renderCardInfo: (data) => <p>{data.description}</p>,
      searchConditions: [{
         conditionType: 'AND',
         conditionString: 'clientid:1021'
      }],
      formatHitURL: (data) => `/${data.slug}`,
    }]}
    searchOperators={['<', '=', '>', '>=', '<=']}
    specialChar=":"
    scrollWindowHeight={200}
    customLoader={<p>Loading...</p>}
    customNoResults={<p>No results...</p>}
/>
```

I think there are still a few improvements that can still be made, but the majority of the Component is built. 

Please provide any feedback that you would like to see implemented into this component and I'm sure we can make it work!

Please note that you should _never_ commit the `ALGOLIA_APP_ID` or the `ALGOLIA_API_SEARCH_KEY` to the repository, so if you enter them to test it out in Storybook, please be sure to remove them if you plan to commit!

### CODE REVIEW

**Comment by JarrodMFlesch** [comment]
@esoubihe I believe I have addressed all of your issues from https://github.com/trouble/metal-ui/pull/2

Let me know if I missed anything!

**Comment by esoubihe** [comment]
Thanks, @JarrodMFlesch. We're automating the release process now. Do you mind syncing with master and rebuilding the project with `npm run build` to fix the conflicts?

**Comment by robsoncoelho** [comment]
@JarrodMFlesch and @esoubihe there are some conflicts to resolve due the latest push to master

**Comment by JarrodMFlesch** [comment]
@robsoncoelho should be all good now 👍

**Review by robsoncoelho — APPROVED** [review]

**Pull request merged**
